package mx.com.sunset.heimdall.ui.view.configurationProfile;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ConfigurationProfileViewDesign extends VerticalLayout {
	protected TextField search;
	protected Button add;
	protected Grid<mx.com.sunset.heimdall.backend.data.entity.ConfigurationProfile> list;
	protected VerticalLayout form;
	protected TextField name;
	protected TextField database_server;
	protected TextField port;
	protected TextField scheme;
	protected TextField driver_class;
	protected TextField email_server;
	protected TextField email_user;
	protected TextField email_password;
	protected TextField email_port;
	protected TextField db_user;
	protected TextField db_password;
	protected TextField url;
	protected Button update;
	protected Button cancel;
	protected Button delete;

	public ConfigurationProfileViewDesign() {
		Design.read(this);
	}
}
